image:
  file: .gitpod.Dockerfile
tasks:
  - name: Preparation (Python and nodejs dependencies)
    init: |
      python3.9 -m venv venv
      source venv/bin/activate
      pip install -r requirements.txt
      cd axios-test
      npm i
      cd ..
    command: echo 'Done!'